{
	"openapi": "3.0.0",
	"info": {
		"title": "مستندات سرویس‌های پلتفرم مالی پی‌پینگ",
		"description": "# پشتیبانی\n\n تلگرام: [t.me/PayPingSupport](https://t.me/PayPingSupport) \n\n ایمیل: [info@payping.ir]() \n\n تلفن: 02191001520\n # مقدمه\n\n تمامی وب‌ سرویس‌های توضیح داده شده در این مستندات به صورت [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer) هستند و طبق همین چهارچوب باید با آنها ارتباط برقرار کرد.    \n جهت رفع هرگونه مشکل و یا پرسش با پشتیبانی در تماس باشید.\n\n # POSTMAN\n برای راحتی کار شما فایل postman سرویس ها برای شما آماده شده است که می تو[...]",
		"version": "v1-v2",
		"x-logo": {
			"url": "https://cdn.payping.ir/statics/Payping-logo/full%20logo/english/fullcolor/SVG/payping.svg"
		}
	},
	"servers": [
		{
			"url": "https://api.payping.ir/"
		}
	],
	"security": [
		{
			"Bearer": [
				"profile",
				"email",
				"nationalcode",
				"birthday",
				"shaba",
				"phone",
				"pay:read",
				"pay:write",
				"product:read",
				"product:write",
				"customer:read",
				"customer:write",
				"invoice:read",
				"invoice:write",
				"coupon:read",
				"coupon:write",
				"upload:write"
			]
		},
		{
			"oauth2": [
				"profile",
				"email",
				"nationalcode",
				"birthday",
				"shaba",
				"phone",
				"pay:read",
				"pay:write",
				"product:read",
				"product:write",
				"customer:read",
				"customer:write",
				"invoice:read",
				"invoice:write",
				"coupon:read",
				"coupon:write",
				"upload:write"
			]
		}
	],
	"tags": [
		{
			"name": "Payment",
			"description": "متدهای مرتبط با تراکنش‌های مالی که شامل پرداخت پول، پرداخت تسهیمی و تمام فرآیندهای تایید یک تراکنش می‌باشد."
		},
		{
			"name": "Request",
			"description": "متدهای مرتبط با درخواست پول از دیگران به صورتیکه برای آنها یک لینک پرداخت به صورت ایمیل و یا پیامک ارسال می‌شود."
		},
		{
			"name": "Withdraw",
			"description": "متدهای مرتبط با درخواست تسویه حساب."
		},
		{
			"name": "Report",
			"description": "متدهای مرتبط با گزارش تراکنش‌های درخواست و یا پرداخت پول."
		},
		{
			"name": "Product",
			"description": "سرویس‌های عمومی بخش آیتم‌های مالی، لینک ثابت و سرویس‌های مربوط به پروسه پرداخت آنها"
		},
		{
			"name": "PermaLink",
			"description": "سرویس‌های  لینک ثابت آیتم مالی"
		},
		{
			"name": "coupon",
			"description": "سرویس‌های عمومی بخش کدهای تخفیف"
		},
		{
			"name": "Customer",
			"description": "در این بخش میتوانید مشتریان خود را به صورت یک دفترچه سنتی مدیریت و در زمان صدور فاکتور از این لیست استفاده کنید."
		},
		{
			"name": "Invoice",
			"description": "در این بخش میتوانید فاکتور بسازید و با انتخاب یک یا چند مشتری و حتی پست الکترونیک برای آنها فاکتور را ارسال کنید تا نسبت به پرداخت آن اقدام کنند."
		},
		{
			"name": "Schedule",
			"description": "در این بخش میتوانید فاکتور های زمانبندی شده بسازید و با انتخاب یک یا چند مشتری و حتی پست الکترونیک برای آنها فاکتور را ارسال کنید تا نسبت به پرداخت آن اقدام کنند."
		},
		{
			"name": "Upload",
			"description": "متدهای مرتبط با [آپلود فایل‌ها](#section/) ورودی تمام این سرویس‌ها به صورت formData می‌باشد."
		}
	],
	"paths": {
		"/v2/pay": {
			"post": {
				"tags": ["Payment"],
				"summary": "ساخت پرداخت",
				"description": " به کمک این متد می توانید برای یک نفر کد پرداخت ایجاد کنید. \n  فراخوانی این متد برای شما کدی یکتا تولید می کند. \n  پس از ساخت یک پرداخت، برای ورود به درگاه بانک تنها کافیست کاربر را به همراه کد ساخته شده به آدرس https://api.payping.ir/v2/pay/gotoipg/{code} هدایت نمایید. \n  پس از اتمام فرایند در درگاه بانکی، اطلاعات پرداخت به آدرس `returnUrl` که در مرحله اول (ساخت پرداخت) مشخص شده است در بدنه درخواست بصورت زیر فرستاده می‌شود \n ```  curl --location --request POST 'YOUR-retu[...]",
				"operationId": "CreateSinglePayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v2/pay/verify": {
			"post": {
				"tags": ["Payment"],
				"summary": "تایید پرداخت",
				"description": "از این متد برای تایید پرداخت موفق پس از بازگشت از درگاه بانکی استفاده می شود.\r\nدر صورتی که این متد تا 10 دقیقه پس از پرداخت فراخوانی نشود پرداخت باطل شده و پول به حساب پرداخت کننده باز خواهد گشت",
				"operationId": "VerifyPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v2/pay/multi": {
			"post": {
				"tags": ["Payment"],
				"summary": "ساخت پرداخت تسهیمی",
				"description": "به کمک این متد می توانید برای یک پرداخت چند نفره (تسهیمی) کد پرداخت ایجاد کنید.\r\nفراخوانی این متد برای شما یک کد 4 حرفی تولید می کند.\r\nپس از ساخت یک پرداخت، برای ورود به درگاه بانک تنها کافیست کاربر را به همراه کد ساخته شده به آدرس https://api.payping.ir/v2/pay/gotoipg/{code} هدایت نمایید.\r\nپس از اتمام فرایند در درگاه بانکی، کاربر به آدرسی که در ReturnUrl توسط شما مشخص شده است هدایت می شود\r\nکه حاوی دو پارامتر Refid, ClientRefId در قسمت QueryString آدرس می باشد.\r\nRef[...]",
				"operationId": "CreateMultiPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v2/pay/BlockMoney": {
			"post": {
				"tags": ["Payment"],
				"summary": "ساخت پرداخت مسدود شده",
				"description": "به کمک این متد می تواندی برای پرداخت به چند نفر، کد پرداخت تولید کنید، که \r\nاین یک پرداخت مسدود شده می باشد و امکان جابجایی آن تا فراخوانی متد UnBlockMoney امکان پذیر نمی باشد.",
				"operationId": "CreateBlockPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v2/pay/UnBlockMoney": {
			"post": {
				"tags": ["Payment"],
				"summary": "آزاد سازی پول مسدود شده",
				"description": "به کمک این متد، می توانید پول مسدود شده توسط متد BlockMoney را از حالت مسدودی آزاد نمایید.",
				"operationId": "UnBlockPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/pos": {
			"post": {
				"tags": ["Payment"],
				"summary": "ساخت پرداخت شناسه دار",
				"description": "از این متد می تواند برای ساخت یک پرداخت شناسه دار که به کمک دستگاه Pos پرداخت آن انجام می شود، استفاده کرد",
				"operationId": "CreateIdPosPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v2/pay/{code}": {
			"delete": {
				"tags": ["Payment"],
				"summary": "برای لغو کردن یک کد پرداخت می توانید از این متد استفاده کنید",
				"operationId": "CancelPayment",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/report/TransactionReport": {
			"post": {
				"tags": ["Report"],
				"summary": "گزارش تراکنش ها",
				"description": "از این متد برای نمایش جزئیات تراکنش های کاربر استفاده می شود",
				"operationId": "TransactionsReport",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/report/TransactionReportCount": {
			"post": {
				"tags": ["Report"],
				"summary": "تعداد تراکنش ها",
				"description": "از این متد برای نمایش تعداد تراکنش های برگشت داده شده از متد TransactionReport استفاده می شود",
				"operationId": "TransactionsReportCount",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/report/WithdrawTransactions": {
			"post": {
				"tags": ["Report"],
				"summary": "دریافت لیست تسویه حساب",
				"description": "به کمک این متد می توانید لیست درخواست های تسویه شده و در انتظار تسویه را نمایش دهید",
				"operationId": "WithdrawTransactionsReport",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/report/WithdrawTransactionsCount": {
			"post": {
				"tags": ["Report"],
				"summary": "تعداد لیست تسویه حساب",
				"description": "به کمک این متد می توانید تعداد لیست درخواست های تسویه شده و در انتظار تسویه را که از متد WithdrawTransactions دریافت کرده اید را نمایش دهید",
				"operationId": "WithdrawTransactionsCount",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/report/{code}": {
			"get": {
				"tags": ["Report"],
				"summary": "نمایش جزئیات تراکنش",
				"operationId": "GetPaymentDetails",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/request": {
			"post": {
				"tags": ["Request"],
				"summary": "ارسال درخواست پول",
				"description": "از این متد برای ارسال لینک درخواست پول برای یک نفر بصورت  پیامک یا ایمیل استفاده می شود",
				"operationId": "CreateRequest",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/request/multi": {
			"post": {
				"tags": ["Request"],
				"summary": "ارسال درخواست پول برای چند نفر",
				"description": "از این متد برای ارسال لینک درخواست پول برای چند نفر بصورت  پیامک یا ایمیل استفاده می شود",
				"operationId": "CreateMultiRequest",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/request/{code}/SendReminder": {
			"post": {
				"tags": ["Request"],
				"summary": "یادآوری مجدد درخواست پول",
				"description": "از این متد برای ارسال مجدد پیامک یا ایمیل لینک درخواست پول استفاده می شود",
				"operationId": "SendReminder",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/request/{code}": {
			"delete": {
				"tags": ["Request"],
				"summary": "لغو درخواست پول",
				"description": "برای لغو کردن یک کد درخواست می توانید از این متد استفاده کنید",
				"operationId": "CancelRequest",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/withdraw/{amount}": {
			"post": {
				"tags": ["Withdraw"],
				"summary": "درخواست تسویه حساب",
				"description": "به کمک این متد می توانید یک درخواست تسویه با مبلغ دلخواه ایجاد نمایید",
				"operationId": "CreateWithdraw",
				"security": [
					{
						"Bearer": ["pay:write"]
					},
					{
						"oauth2": ["pay:write"]
					}
				]
			}
		},
		"/v1/withdraw/{code}": {
			"get": {
				"tags": ["Withdraw"],
				"summary": "نمایش جزئیات درخواست تسویه",
				"description": "از این متد برای نمایش لیست تسویه ها",
				"operationId": "GetWithdrawDetails",
				"security": [
					{
						"Bearer": ["pay:read"]
					},
					{
						"oauth2": ["pay:read"]
					}
				]
			}
		},
		"/v1/customer": {
			"post": {
				"tags": ["Customer"],
				"summary": "مشتری جدید",
				"operationId": "CreateCustomer",
				"security": [
					{
						"Bearer": ["customer:write"]
					},
					{
						"oauth2": ["customer:write"]
					}
				]
			}
		},
		"/v1/customer/{code}": {
			"get": {
				"tags": ["Customer"],
				"summary": "مشخصات مشتری",
				"operationId": "GetCustomerDetails",
				"security": [
					{
						"Bearer": ["customer:read"]
					},
					{
						"oauth2": ["customer:read"]
					}
				]
			},
			"put": {
				"tags": ["Customer"],
				"summary": "بروزرسانی مشخصات مشتری",
				"operationId": "EditCustomer",
				"security": [
					{
						"Bearer": ["customer:write"]
					},
					{
						"oauth2": ["customer:write"]
					}
				]
			},
			"delete": {
				"tags": ["Customer"],
				"summary": "حذف مشتری",
				"operationId": "DeleteCustomer",
				"security": [
					{
						"Bearer": ["customer:write"]
					},
					{
						"oauth2": ["customer:write"]
					}
				]
			}
		},
		"/v1/customer/List": {
			"get": {
				"tags": ["Customer"],
				"summary": "لیست مشتریان",
				"operationId": "GetCustomerList",
				"security": [
					{
						"Bearer": ["customer:read"]
					},
					{
						"oauth2": ["customer:read"]
					}
				]
			}
		},
		"/v1/customer/ListCount": {
			"get": {
				"tags": ["Customer"],
				"summary": "تعداد مشتریان",
				"operationId": "GetCustomerListCount",
				"security": [
					{
						"Bearer": ["customer:read"]
					},
					{
						"oauth2": ["customer:read"]
					}
				]
			}
		},
		"/v1/coupon": {
			"post": {
				"tags": ["coupon"],
				"summary": "ساخت یک کد تخفیف جدید",
				"operationId": "CreateCoupon",
				"security": [
					{
						"Bearer": ["coupon:write"]
					},
					{
						"oauth2": ["coupon:write"]
					}
				]
			},
			"put": {
				"tags": ["coupon"],
				"summary": "بروزرسانی کد تخفیف",
				"operationId": "EditCoupon",
				"security": [
					{
						"Bearer": ["product:write"]
					},
					{
						"oauth2": ["product:write"]
					}
				]
			}
		},
		"/v1/coupon/{code}": {
			"get": {
				"tags": ["coupon"],
				"summary": "نمایش یک کد تخفیف",
				"operationId": "GetCouponDetails",
				"security": [
					{
						"Bearer": ["coupon:read"]
					},
					{
						"oauth2": ["coupon:read"]
					}
				]
			},
			"delete": {
				"tags": ["coupon"],
				"summary": "حذف یک کد تخفیف",
				"operationId": "DeleteCoupon",
				"security": [
					{
						"Bearer": ["coupon:write"]
					},
					{
						"oauth2": ["coupon:write"]
					}
				]
			}
		},
		"/v1/coupon/List": {
			"get": {
				"tags": ["coupon"],
				"summary": "نمایش لیست کدهای تخفیف",
				"operationId": "GetCouponList",
				"security": [
					{
						"Bearer": ["coupon:read"]
					},
					{
						"oauth2": ["coupon:read"]
					}
				]
			}
		},
		"/v1/coupon/ListCount": {
			"get": {
				"tags": ["coupon"],
				"summary": "دریافت تعداد کدهای تخفیف",
				"operationId": "GetCouponListCount",
				"security": [
					{
						"Bearer": ["coupon:read"]
					},
					{
						"oauth2": ["coupon:read"]
					}
				]
			}
		},
		"/v1/coupon/{couponCode}/BuyersListCount": {
			"get": {
				"tags": ["coupon"],
				"summary": "دریافت تعداد خرید‌های یک کد تخفیف",
				"operationId": "GetCouponBuyersCount",
				"security": [
					{
						"Bearer": ["coupon:read"]
					},
					{
						"oauth2": ["coupon:read"]
					}
				]
			}
		},
		"/v1/coupon/{couponCode}/BuyersList": {
			"get": {
				"tags": ["coupon"],
				"summary": "دریافت لیست پرداخت‌های انجام شده یک کد تخفیف",
				"operationId": "GetCouponBuyersList",
				"security": [
					{
						"Bearer": ["coupon:read"]
					},
					{
						"oauth2": ["coupon:read"]
					}
				]
			}
		},
		"/v1/product": {
			"post": {
				"tags": ["Product"],
				"summary": "ساخت یک آیتم‌ مالی جدید",
				"operationId": "CreateProduct",
				"security": [
					{
						"Bearer": ["product:write"]
					},
					{
						"oauth2": ["product:write"]
					}
				]
			},
			"put": {
				"tags": ["Product"],
				"summary": "بروزرسانی آیتم مالی",
				"operationId": "EditProduct",
				"security": [
					{
						"Bearer": ["product:write"]
					},
					{
						"oauth2": ["product:write"]
					}
				]
			}
		},
		"/v1/product/{code}": {
			"get": {
				"tags": ["Product"],
				"summary": "نمایش یک آیتم مالی",
				"operationId": "GetProductDetails",
				"security": [
					{
						"Bearer": ["product:read"]
					},
					{
						"oauth2": ["product:read"]
					}
				]
			},
			"delete": {
				"tags": ["Product"],
				"summary": "حذف یک آیتم مالی",
				"operationId": "DeleteProduct",
				"security": [
					{
						"Bearer": ["product:write"]
					},
					{
						"oauth2": ["product:write"]
					}
				]
			}
		},
		"/v1/product/List": {
			"get": {
				"tags": ["Product"],
				"summary": "دریافت لیست آیتم‌های مالی",
				"operationId": "GetProductList",
				"security": [
					{
						"Bearer": ["product:read"]
					},
					{
						"oauth2": ["product:read"]
					}
				]
			}
		},
		"/v1/permalink": {
			"post": {
				"tags": ["PermaLink"],
				"summary": "ساخت لینک ثابت برای یک آیتم مالی"
			},
			"put": {
				"tags": ["PermaLink"],
				"summary": "ویرایش لینک ثابت یک آیتم مالی"
			}
		},
		"/v1/permalink/{code}": {
			"delete": {
				"tags": ["PermaLink"],

				"summary": "حذف لینک ثابت برای یک آیتم مالی"
			},
			"get": {
				"tags": ["PermaLink"],
				"operationId": "GetPermaList",
				"summary": "دریافت اطلاعات لینک ثابت ",
				"security": [
					{
						"Bearer": ["product:read"]
					},
					{
						"oauth2": ["product:read"]
					}
				]
			}
		},
		"/v1/permalink/{productCode}/BuyersList": {
			"get": {
				"tags": ["PermaLink"],
				"summary": "دریافت لیست اطلاعات خریداران یک آیتم مالی دارای لینک ثابت"
			}
		},
		"/v1/permalink/{productCode}/BuyersListCount": {
			"get": {
				"tags": ["PermaLink"],
				"summary": "دریافت تعداد لیست اطلاعات خریداران یک آیتم مالی دارای لینک ثابت"
			}
		},
		"/v1/permalink/{payCode}/Buyer": {
			"get": {
				"tags": ["PermaLink"],
				"summary": "دریافت اطلاعات خریدار مربوط به یک کد پرداخت"
			}
		},
		"/v2/invoice": {
			"post": {
				"tags": ["Invoice"],
				"summary": "فاکتور جدید",
				"operationId": "CreateInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			}
		},
		"/v2/invoice/Send/{code}": {
			"post": {
				"tags": ["Invoice"],
				"summary": "ارسال فاکتور",
				"operationId": "SendInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			}
		},
		"/v2/invoice/{code}": {
			"put": {
				"tags": ["Invoice"],
				"summary": "بروزرسانی فاکتور",
				"operationId": "EditInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			},
			"delete": {
				"tags": ["Invoice"],
				"summary": "حذف فاکتور",
				"operationId": "DeleteInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			},
			"get": {
				"tags": ["Invoice"],
				"summary": "دریافت فاکتور",
				"operationId": "GetInvoiceDetails",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/Pdf/{code}": {
			"get": {
				"tags": ["Invoice"],
				"summary": "فاکتور غیر رسمی pdf درخواست",
				"operationId": "GetInvoicePdf",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/List": {
			"get": {
				"tags": ["Invoice"],
				"summary": "لیست فاکتور ها",
				"operationId": "GetInvoiceList",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/ListCount": {
			"get": {
				"tags": ["Invoice"],
				"summary": "تعداد فاکتور ها",
				"operationId": "GetInvoiceListCount",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/Copy": {
			"post": {
				"tags": ["Invoice"],
				"summary": "کپی یک فاکتور برای مشتری جدید"
			}
		},
		"/v2/invoice/Cancel": {
			"post": {
				"tags": ["Invoice"],
				"summary": "درخواست لغو فاکتور",
				"operationId": "CancelInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			}
		},
		"/v2/invoice/CancelSchedule": {
			"post": {
				"tags": ["Invoice"],
				"summary": "لغو زمانبندی یک فاکتور"
			}
		},
		"/v2/invoice/Reminder/{code}": {
			"post": {
				"tags": ["Invoice"],
				"summary": "ارسال یادآوری فاکتور",
				"operationId": "RemindeInvoice",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			}
		},
		"/v2/invoice/Schedule": {
			"post": {
				"tags": ["Schedule"],
				"summary": "فاکتور زمانبندی شده جدید",
				"operationId": "CreateInvoiceSchedule",
				"security": [
					{
						"Bearer": ["invoice:write"]
					},
					{
						"oauth2": ["invoice:write"]
					}
				]
			}
		},
		"/v2/invoice/Schedule/{code}": {
			"get": {
				"tags": ["Schedule"],
				"summary": "دریافت فاکتور زمانبندی شده",
				"operationId": "GetInvoiceSchedule",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/ListSchedule": {
			"get": {
				"tags": ["Schedule"],
				"summary": "لیست فاکتور ها زمانبندی شده",
				"operationId": "GetInvoiceListSchedule",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/ListScheduleCount": {
			"get": {
				"tags": ["Schedule"],
				"summary": "تعداد فاکتور ها زمانبندی شده",
				"operationId": "GetInvoiceListScheduleCount",
				"security": [
					{
						"Bearer": ["invoice:read"]
					},
					{
						"oauth2": ["invoice:read"]
					}
				]
			}
		},
		"/v2/invoice/PaymentCode": {
			"get": {
				"tags": ["Invoice"],
				"summary": "دریافت کد پرداخت برای یک فاکتور"
			}
		},
		"/v2/invoice/ConfirmPayment": {
			"post": {
				"tags": ["Invoice"],
				"summary": "تایید پرداخت یک فاکتور"
			}
		},
		"/v2/invoice/FastInvoice": {
			"post": {
				"tags": ["Invoice"],
				"summary": "ساخت همزمان فاکتور و مشتری و دریافت کد پرداخت"
			}
		},

		"/v1/upload/ProfilePic": {
			"post": {
				"tags": ["Upload"],
				"summary": "آپلود عکس پروفایل کاربری",
				"description": "محدودیت‌های فایل‌های ورودی:\r\n\r\nJPG, PNG, JPEG",
				"operationId": "UploadProfilePic",
				"security": [
					{
						"Bearer": ["upload:write"]
					},
					{
						"oauth2": ["upload:write"]
					}
				]
			}
		},
		"/v1/upload/Item": {
			"post": {
				"tags": ["Upload"],
				"summary": "آپلود عکس یک آیتم‌مالی",
				"description": "محدودیت‌های فایل‌های ورودی:\r\n\r\nJPG, PNG, JPEG",
				"operationId": "UploadItem",
				"security": [
					{
						"Bearer": ["upload:write"]
					},
					{
						"oauth2": ["upload:write"]
					}
				]
			}
		},
		"/v1/upload/InvoiceAttachment": {
			"post": {
				"tags": ["Upload"],
				"summary": "آپلود فایل‌ ضمیمه یک فاکتور",
				"description": "محدودیت‌های فایل‌های ورودی:\r\n\r\nمحدودیت ندارد.",
				"operationId": "UploadInvoiceAttachment",
				"security": [
					{
						"Bearer": ["upload:write"]
					},
					{
						"oauth2": ["upload:write"]
					}
				]
			}
		}
	},
	"components": {
		"securitySchemes": {
			"Bearer": {
				"type": "apiKey",
				"description": "برای احراز هویت در سرویس‌های مختلف باید از توکن Bearer در header درخواست‌ها به صورت زیر استفاده کنید \n\n\n ساختار ارسال توکن: (Bearer TOKEN) \n\n\n  اگر شما یک اپلیکیشن و یا وب‌سایت شخصی دارید و قصد استفاده از سرویس‌های مالی ما را برای خود دارید می‌بایست از access token استفاده کنید،  جهت مطالعه روند دریافت آن از کنسول توسعه‌دهنده،   [لطفا اینجا کلیک نمایید.](https://www.payping.io/help/fa/nhoh-driaft-tokn-akhtsasi/)",
				"name": "Authorization",
				"in": "header"
			},
			"oauth2": {
				"type": "oauth2",
				"description": "اما اگر وب‌سایت و اپلیکیشن شما قصد دسترسی به اطلاعات سایر کاربران پی‌پینگ را دارد، شما می‌بایست از سرویس OAuth ما استفاده کنید که به شما اجازه یک احراز هویت امن با استفاده از یک متد استاندارد و ساده به اپلیکیشن‌های وب، موبایل و دسکتاپ میدهد. جهت مطالعه روند اعطای دسترسی و روند کار [لطفا اینجا کلیک نمایید.](https://www.payping.io/help/fa/nhoh-driaft-tokn-akhtsasi/)",
				"flows": {
					"authorizationCode": {
						"authorizationUrl": "https://oauth.payping.ir/connect/authorize",
						"tokenUrl": "https://oauth.payping.ir/connect/token",
						"scopes": {
							"profile": "دسترسی مرتبط با تمام اطلاعات یک کاربر",
							"email": "دسترسی به مشاهده ایمیل",
							"nationalcode": "دسترسی به مشاهده کدملی کاربر",
							"birthday": "دسترسی به مشاهده تاریخ تولد کاربر",
							"shaba": "دسترسی به مشاهده شبای بانکی کاربر",
							"phone": "دسترسی به مشاهده شماره تماس کاربر",
							"pay:read": "دسترسی فقط خواندنی در سرویس پرداخت",
							"pay:write": "دسترسی نوشتن و تغییرات در سرویس پرداخت",
							"product:read": "دسترسی فقط خواندنی در سرویس آیتم‌های مالی",
							"product:write": "دسترسی نوشتن و تغییرات در سرویس آیتم‌های مالی",
							"coupon:read": "دسترسی فقط خواندنی در سرویس کد تخفیف",
							"coupon:write": "دسترسی فقط خواندنی در سرویس کد تخفیف",
							"customer:read": "دسترسی نوشتن و تغییرات در سرویس مشتریان",
							"customer:write": "دسترسی نوشتن و تغییرات در سرویس مشتریان",
							"invoice:read": "دسترسی فقط خواندنی به سرویس فاکتور ها",
							"invoice:write": "دسترسی نوشتن و تغییرات در سرویس فاکتور ها",
							"upload:write": "دسترسی مرتبط با سرویس بارگذاری فایل‌ها"
						}
					}
				}
			}
		}
	},
	"x-tagGroups": [
		{
			"name": "سرویس پرداخت",
			"tags": ["Payment", "Request", "Withdraw", "Report"]
		},
		{
			"name": "سرویس مشتریان",
			"tags": ["Customer"]
		},
		{
			"name": "سرویس آیتم‌های مالی",
			"tags": ["Product", "PermaLink", "coupon"]
		},
		{
			"name": "سرویس فاکتور",
			"tags": ["Invoice", "Schedule"]
		},
		{
			"name": "سرویس آپلود فایل",
			"tags": ["Upload"]
		}
	]
}
